### ISSUE TITLE
It is about training..

### ISSUE THREAD

**Issue by vps62** [parilo/DeepTraffic-solution#3]
Hi Parilo,
Thank you for the code. As I am new in this field. can you please explain that how did you get the values of brain?
Thank you.

**Comment by parilo** [comment]
What do you mean by values of brain? If you mean number of layers and neurons per layer, so I have some empirical experience. I'm not pretend to optimality :) So try different and see what happens. But change only one parameter per experiment ;)

**Comment by vps62** [comment]
Thank you for the reply. I was telling about the last two lines. 
if (brain) {
brain.value_net.fromJSON({"layers":[{"out_depth":420,"out_sx":1,"out_sy":1,"layer_type":"input"},{"out_depth":36,"out_sx":1,"out_sy":1,"layer_type":"fc","num_inputs":420,"l1_.....................}

**Comment by parilo** [comment]
I've trained it on deeptraffic website
