### ISSUE TITLE
I am facing a very strange problem, car stops after the reward reach >1

### ISSUE THREAD

**Issue by hahakid** [parilo/DeepTraffic-solution#4]
My car/cars will stop running after training for a while, the reward first rises and then drops slowly to negative and the speed drops to zero even if there is no car blocks behind. Do you have any idea about this?

**Comment by parilo** [comment]
Do you use my code? Or your own? If you use my, I think that main website code may change have became compatible. It may helps if you just try to apply my changes one by one to the default solution.

**Comment by hahakid** [comment]
Thanks for you response, I am in China, and maybe this is caused by the internet problem, some of the buttons on the website of deepTraffic may dead, I will try later when I use a VPN. And I can try yours first.
